apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: chalk-board-namespace
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chalkboard-secret
                  key: GRAFANA_PASSWORD
            - name: GF_INSTALL_PLUGIN
              value: "grafana-clock-panel,grafana-simple-json-datasource"
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: "Admin"
            - name: GF_FEATURE_TOGGLES_ENABLE
              value: "traceqlEditor"
            - name: GF_SERVER_ROOT_URL
              value: "http://gateway-service/grafana/" # Ensure this is correct for your environment
          ports:
            - containerPort: 3000
              name: http
          volumeMounts:
            - name: grafana-data
              mountPath: /var/lib/grafana
            - name: grafana-datasource-config
              mountPath: /etc/grafana/provisioning/datasources/grafana-datasource.yml
              subPath: grafana-datasource.yml
            - name: grafana-dashboard-provisioning
              mountPath: /etc/grafana/provisioning/dashboards/grafana-dashboard.yml
              subPath: grafana-dashboard.yml
            - name: grafana-dashboards
              mountPath: /etc/grafana/dashboards
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 10
      volumes:
        - name: grafana-datasource-config
          configMap:
            name: grafana-datasource-config
        - name: grafana-dashboard-provisioning
          configMap:
            name: grafana-dashboard-provisioning
        - name: grafana-dashboards
          configMap:
            name: grafana-dashboards
        - name: grafana-data
          persistentVolumeClaim:
            claimName: grafana-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: chalk-board-namespace
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: chalk-board-namespace
  labels:
    app: grafana
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: grafana
