apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-all-in-one
  namespace: chalk-board-namespace
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger-all-in-one
          image: jaegertracing/all-in-one:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 16686
              name: query-http
            - containerPort: 14268
              name: collector-http
            - containerPort: 14250
              name: collector-grpc
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-all-in-one
  namespace: chalk-board-namespace
  labels:
    app: jaeger
spec:
  type: ClusterIP
  ports:
    - port: 16686
      targetPort: query-http
      protocol: TCP
      name: query-http
    - port: 14268
      targetPort: collector-http
      protocol: TCP
      name: collector-http
    - port: 14250
      targetPort: collector-grpc
      protocol: TCP
      name: collector-grpc
  selector:
    app: jaeger
