apiVersion: v1
kind: ConfigMap
metadata:
  name: learning-service-config
  namespace: chalk-board-namespace
data:
  application.yml: |
    spring:
      application:
        name: learning-service
      lifecycle:
        timeout-per-shutdown-phase: 15s
      datasource:
        url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/chalk_board}
        username: ${SPRING_DATASOURCE_USERNAME:username}
        password: ${SPRING_DATASOURCE_PASSWORD:password}
        hikari:
          connection-timeout: 20000
          maximum-pool-size: 20
          minimum-idle: 5
      jpa:
        hibernate:
          ddl-auto: update
        show-sql: false
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:-http://chalk-keycloak:7080/realms/chalk-board}
    
    server:
      port: 8081
      shutdown: graceful
      tomcat:
        connection-timeout: 2s
        keep-alive-timeout: 15s
        threads:
          max: 50
          min-spare: 5

    logging:
      pattern:
        level: ${LOGGING_LEVEL_PATTERN_LS:"%5p [${spring.application.name},%X{trace_id},%X{span_id}]"}
      level:
        com.jsl: DEBUG
        org.springframework.web: INFO
        org.springframework.security: INFO

    management:
      endpoints:
        web:
          base-path: ${MANAGEMENT_WEB_ENDPOINT_BASE_LS:/learning-service-management}
          exposure:
            include: ${MANAGEMENT_ENDPOINT_INCLUDE:health,info,metrics,prometheus,refresh}
      endpoint:
        health:
          show-details: when_authorized
          probes.enabled: true
      info:
        java.enabled: true
        os.enabled: true
        env.enabled: true
        git.mode: full
      
      otlp:
        metrics:
          export:
            url: ${OTEL_COLLECTOR_METRICS_URL:http://otel-collector:4318/v1/metrics}
            step: 10s
        tracing:
          endpoint: ${OTEL_COLLECTOR_TRACES_URL:http://otel-collector:4318/v1/traces}

      tracing:
        sampling:
          probability: 1.0
        enabled: true

      metrics:
        tags:
          department: ${SERVICE_DEPARTMENT_LS:learning-service}
          team: ${SERVICE_TEAM_LS:learning-service-team}
          service: ${spring.application.name}
          env: ${SERVICE_ENVIRONMENT:development}
          region: ${SERVICE_REGION:europe-west1}
          instance.id: ${SERVICE_INSTANCE_ID:instances}

        distribution:
          percentiles:
            http.server.requests: 0.99, 0.95, 0.9, 0.7, 0.5
            course.creation.metric: 0.99, 0.95, 0.9, 0.7, 0.5
          percentiles-histogram:
            http.server.requests: true
            course.creation.metric: true
          minimum-expected-value:
            http.server.requests: 100ms
            course.creation.metric: 100ms
          maximum-expected-value:
            http.server.requests: 10s
            course.creation.metric: 10s
          slo:
            http.server.requests: 300ms,500ms,1s,2s
            course.creation.metric: 300ms,500ms,1s,2s
