apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: chalk-board-namespace
data:
  local-config.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100
      grpc_listen_port: 9095
      http_listen_address: 0.0.0.0

    common:
      instance_addr: 127.0.0.1
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory

    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v12
          index:
            prefix: index_
            period: 24h

    storage_config:
      boltdb_shipper:
        active_index_directory: /loki/boltdb-shipper-active
        cache_location: /loki/boltdb-shipper-cache
        # `shared_store` is an attribute of `boltdb_shipper`, but for the `filesystem` it's not nested.
        # It was likely mispositioned due to older config examples.
        shared_store: filesystem
      filesystem:
        directory: /loki/chunks

    limits_config:
      allow_structured_metadata: true
      max_streams_per_user: 100000
      max_global_streams_per_user: 100000

    ruler:
      alertmanager_url: http://localhost:9093

    analytics:
      reporting_enabled: false
