apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: chalk-board-namespace
data:
  local-config.yaml: |
    # Paste the content of your local-config.yaml file here
    auth_enabled: false
    # https://grafana.com/docs/loki/latest/configure/#limits_config
    limits_config:
      allow_structured_metadata: true
      max_streams_per_user: 100000
      max_global_streams_per_user: 100000

    server:
      http_listen_port: 3100

    common:
      instance_addr: 127.0.0.1
      path_prefix: /var/loki
      storage:
        filesystem:
          chunks_directory: /var/loki/chunks
          rules_directory: /var/loki/rules
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory

    schema_config:
      configs:
        - from: 2020-10-24
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h

    # ruler:  # Commented out until alertmanager is deployed
      # alertmanager_url: http://alertmanager:9093
    analytics:
      reporting_enabled: false