apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-dev
  namespace: chalk-board-namespace
  labels:
    app: mail-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mail-dev
  template:
    metadata:
      labels:
        app: mail-dev
    spec:
      containers:
        - name: mail-dev
          image: maildev/maildev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1080
              name: front-http
            - containerPort: 1025
              name: back-http
---
apiVersion: v1
kind: Service
metadata:
  name: mail-dev
  namespace: chalk-board-namespace
  labels:
    app: mail-dev
spec:
  type: ClusterIP
  ports:
    - port: 1080
      targetPort: front-http
      protocol: TCP
      name: front-http
    - port: 1025
      targetPort: back-http
      protocol: TCP
      name: back-http
  selector:
    app: mail-dev
