apiVersion: v1
kind: ConfigMap
metadata:
  name: memcached-config
  namespace: chalk-board-namespace
data:
  MEMCACHED_MAX_MEMORY: "64m"
  MEMCACHED_THREADS: "4"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached
  namespace: chalk-board-namespace
  labels:
    app: memcached
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memcached
  template:
    metadata:
      labels:
        app: memcached
    spec:
      containers:
        - name: memcached
          image: memcached:1.6.38
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 11211
              name: memcached
          envFrom:
            - configMapRef:
                name: memcached-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: memcached
  namespace: chalk-board-namespace
  labels:
    app: memcached
spec:
  type: ClusterIP
  ports:
    - port: 11211
      targetPort: memcached
      protocol: TCP
      name: memcached
  selector:
    app: memcached
