apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: chalk-board-namespace
data:
  otel-collector.yml: |
    # Paste the content of your otel-collector.yml file here
    receivers:
      otlp:
        protocols:
          http:
          grpc:

    processors:
      # batch metrics before sending to reduce API usage
      batch:

    exporters:
      logging:
        loglevel: debug

      loki:
        endpoint: "http://loki/loki/api/v1/push"

      prometheus:
        endpoint: "prometheus"
        const_labels:
          label1: value1

      otlp:
        endpoint: "tempo" # tor Tempo
        tls:
          insecure: true

      zipkin:
        endpoint: "http://zipkin-all-in-one/api/v2/spans"
        format: proto

      jaeger:
        endpoint: jaeger-all-in-one
        tls:
          insecure: true

    # https://github.com/open-telemetry/opentelemetry-collector/blob/main/extension/README.md
    extensions:
      # responsible for responding to health check calls on behalf of the collector.
      health_check:
      # fetches the collector’s performance data
      pprof:
      # serves as an http endpoint that provides live debugging data about instrumented components.
      zpages:

    service:
      extensions: [health_check, pprof, zpages]
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp,zipkin,jaeger]
        logs:
          receivers: [otlp]
          exporters: [loki]
