apiVersion: batch/v1
kind: Job
metadata:
  name: redis-cluster-creator
  namespace: chalk-board-namespace
spec:
  template:
    spec:
      containers:
        - name: redis-cluster-creator
          image: redis:7-alpine
          command:
            - "sh"
            - "-c"
            - |
              until [ $(redis-cli -h redis-cluster-headless-0.redis-cluster-headless.chalk-board-namespace.svc.cluster.local ping | grep PONG | wc -l) -eq 6 ]; do echo "waiting for redis nodes to be ready..."; sleep 5; done
              redis-cli --cluster create \
                redis-cluster-headless-0.redis-cluster-headless.chalk-board-namespace.svc.cluster.local:6379 \
                redis-cluster-headless-1.redis-cluster-headless.chalk-board-namespace.svc.cluster.local:6379 \
                redis-cluster-headless-2.redis-cluster-headless.chalk-board-namespace.svc.cluster.local:6379 \
                redis-cluster-headless-3.redis-cluster-headless.chalk-board-namespace.svc.cluster.local:6379 \
                redis-cluster-headless-4.redis-cluster-headless.chalk-board-namespace.svc.cluster.local:6379 \
                redis-cluster-headless-5.redis-cluster-headless.chalk-board-namespace.svc.cluster.local:6379 \
                --cluster-replicas 1 \
                --cluster-yes
      restartPolicy: Never
