apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: chalk-board-namespace
data:
  update-node.sh: |
    #!/bin/sh
    set -ex
    HOSTNAME=$(hostname)
    sed "s/{{POD_HOSTNAME}}/$HOSTNAME/g" /tmp/redis.conf > /conf/redis.conf
    exec redis-server /conf/redis.conf

  redis.conf: |
    cluster-enabled yes
    cluster-config-file /data/nodes.conf
    cluster-node-timeout 5000
    appendonly yes
    protected-mode no
    bind 0.0.0.0
    port 6379
