apiVersion: batch/v1
kind: Job
metadata:
  name: redis-cluster-creator
  namespace: chalk-board-namespace
spec:
  template:
    spec:
      containers:
        - name: redis-cluster-creator
          image: redis:7-alpine
          command:
            - "sh"
            - "-c"
            - |
              until [ $(redis-cli -h redis-0.redis.chalk-board-namespace.svc.cluster.local ping | grep PONG | wc -l) -eq 6 ]; do echo "waiting for redis nodes to be ready..."; sleep 5; done
              redis-cli --cluster create \
                redis-0.redis.chalk-board-namespace.svc.cluster.local:6379 \
                redis-1.redis.chalk-board-namespace.svc.cluster.local:6379 \
                redis-2.redis.chalk-board-namespace.svc.cluster.local:6379 \
                redis-3.redis.chalk-board-namespace.svc.cluster.local:6379 \
                redis-4.redis.chalk-board-namespace.svc.cluster.local:6379 \
                redis-5.redis.chalk-board-namespace.svc.cluster.local:6379 \
                --cluster-replicas 1 \
                --cluster-yes
      restartPolicy: Never
